### ISSUE TITLE
Depends on @material-ui/core - doesn't work with @mui/material

### ISSUE THREAD

**Issue by cristianghita24** [kbrueckner/mui-validate#1]
Cannot be used in projects where @mui/material is used as dependency instead of @material-ui/core.

**Comment by kbrueckner** [comment]
My first investigations result in the following:

* TextField, Select and Autocomplete are fully compatible.
* DatePicker input type autodetection is not working - as a workaround it can be set manually by using inputType="picker"
* DatePicker validation functions seem to not work fully as expected.

Investigating further...

@cristianghita24 can you please provide some more details about what is broken in your view?

**Comment by kbrueckner** [comment]
Closing issue since enhancements for compatibility have been put in place.
