### ISSUE TITLE
Cannot update a component (`ValidationGroup`) while rendering a different component (`Validate`). To locate the bad setState() call inside `Validate`

### ISSUE THREAD

**Issue by aman-rawat** [kbrueckner/mui-validate#14]
Getting this warning 

> Cannot update a component (`ValidationGroup`) while rendering a different component (`Validate`). To locate the bad setState() call inside `Validate`

Using it like this 

    <ValidationGroup>
        <form noValidate onSubmit={handleSubmit}>
            <h2>{update ? "Update Company" : "Add Company"}</h2>
            <br/>
             <Validate
                name="name"
                required={true}>
                <TextField
                    fullWidth
                    type="text"
                    name="name"
                    placeholder="Company Name"
                    value={state.name}
                    onChange={handleChange}
                    label="Name"/>
                <AutoDisabler>
                    <InputButton
                        className="w-100 btn btn-primary btn-lg"
                        type="submit"
                        isLoading={addOrEditCompany.isLoading}>
                        {update ? 'Update' : 'Save'}
                    </InputButton>
                </AutoDisabler>
            </Validate>
        </form>
    </ValidationGroup>

**Comment by kbrueckner** [comment]
Am aware of this and looking into finding a solution.

Good to know is: Despite the warning which is thrown there is no other negative impact on the behaviour - also not in a production build.
