### ISSUE TITLE
mui-validate: require is not defined

### ISSUE THREAD

**Issue by Wajeeh-Haider** [kbrueckner/mui-validate#19]
When I deploy my app on netlify. this error occurs

mui-validate: require is not defined
index.cfa5ade3.js:349 mui-validate: No Material UI package found, using the fallback mechanism.

**Comment by kbrueckner** [comment]
This message should be triggered when there is no material ui is installed, either V4 or V5.
Can you double check, that one of those peer dependencies are installed/part of you package.json?

**Comment by Wajeeh-Haider** [comment]
Thsese are my Mui packages and their version.
"@emotion/react": "^11.10.0",
    "@emotion/styled": "^11.10.0",
    "@mui/icons-material": "^5.10.2",
    "@mui/material": "^5.10.2",

And for another mui-validate works on my localhost perfectly but when I deploy it this gives an error mui-validate: require is not defined

**Comment by kbrueckner** [comment]
I suspect that the problem you see goes back to the same reason as mentioned in [here](https://github.com/kbrueckner/mui-validate/issues/15).

Working on getting a version out which is overcoming this.

**Comment by Wajeeh-Haider** [comment]
Okay thanks! That workss
