### ISSUE TITLE
Mui-validate not working in prod: mui-validate: No Material UI package found, using fallback mechanism.

### ISSUE THREAD

**Issue by LucusWebsites** [kbrueckner/mui-validate#21]
Mui-validate is working in my dev envoriment, but when I build my app using Vite I get this error on production: mui-validate: No Material UI package found, using fallback mechanism.

All fields wrapped by \<Validate> dissapear as well.

I tried the following in my .env.production but it didn't help, any ideas?

```
VITE_CI=false
CI=false

**Comment by kbrueckner** [comment]
To be honest, I am not using Vite in my projects and thus have only limited details on how it works.
What I can assume is that it has a problem when there is a dependency not available during build time - which is the case here. mui-validate is supporting both material UI in version 4 and 5, therefore it tries to load both and uses the one being available during the time it tries to access its components during runtime.

You could see if you can configure Vite to still build in that case. As I said i have too less details about Vite to judge if and how that is possible.

I am trying to release an alpha/pre-version of mui-validate v1 soon which then will drop support for material ui version 4. This should ideally solve the issue then. Please bare with me for a few moments and I will get back to you as soon as possible for testing/verifying.

**Comment by kbrueckner** [comment]
I have release an alpha version of version 1 which has the same feature set as 0.3.3 which is designed purely for @mui/material. It doesn't hold that logic with dynamic library loading.

Can you please check out https://www.npmjs.com/package/mui-validate/v/1.0.0-alpha.1 and see if it solves your issues and give me feedback?

**Comment by LucusWebsites** [comment]
> I have released an alpha version of version 1 which has the same feature set as 0.3.3 which is designed purely for @mui/material. It doesn't hold that logic with dynamic library loading.
> 
> Can you please check out https://www.npmjs.com/package/mui-validate/v/1.0.0-alpha.1 and see if it solves your issues and give me feedback?

I have tried version 1.0.0-alpha.1 and it seems to work fine now, cheers!

**Comment by kbrueckner** [comment]
Closing ticket, solved with version 1
