### ISSUE TITLE
Validation skipped for auto filled fields (Chrome)

### ISSUE THREAD

**Issue by LucusWebsites** [kbrueckner/mui-validate#23]
Validation seems to be skipped for fields which are auto filled using Chrome.

Only if I change the value of a field which was auto filled the validation kicks in.

**Comment by LucusWebsites** [comment]
@kbrueckner Can you take a look at this? This is can be very confusing to the user.

It may look like everything is filled correctly when using autofill, but mui-validate does not detect those changes.

**Comment by kbrueckner** [comment]
Will have a look at it but I will need some time for that. If you already have a clue what the issue might be please feel free to drop it here :)

**Comment by kbrueckner** [comment]
I did not yet find a solution for that but will keep you updated in case there is progress.

**Comment by kbrueckner** [comment]
@LucusWebsites is this still an issue/relevant?

**Comment by kbrueckner** [comment]
Closing since no feedback for a while
