### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by cpu0203** [kbrueckner/mui-validate#24]
I am sorry but I can not understand how to use validation. I copied examples and after submitting form nothing happens. Could you show code any working form with validation please?

**Comment by cpu0203** [comment]
No matter. Ok.

**Comment by kbrueckner** [comment]
I am not sure what you mean with "after submitting form nothing happens". Can you explain a little more in detail please.

A very simple code example is:
```javascript
<ValidationGroup>
    <Validate name="myField" required>
        <TextField />
    </Validate>
    <AutoDisabler>
        <Button onClick={() => whatever()}>My Button</Button
    </AutoDisabler>
</ValidationGroup>
```

**Comment by kbrueckner** [comment]
Closing ticket since there is no feedback on it.
